apiVersion: apps/v1
kind: Deployment
metadata:
  name: ha-ticketing-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ha-ticketing-api
  template:
    metadata:
      labels:
        app: ha-ticketing-api
    spec:
      containers:
        - name: api
          image: ha-ticketing-platform:local
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20

